### PR TITLE
Added requirements file to Django sample

### PR DESCRIPTION
**Pull request by pierrei**
Added a requirements file to show which packages are needed to be installed for the Django example to actually work.

To set up a virtual environment with these packages do the following:

```
virtualenv --no-site-packages virtualenv
. virtualenv/bin/activate
pip install -r requirements.txt
```

### CODE REVIEW

**Comment by pierrei** [comment]
I signed it!

**Comment by nathanielmanistaatgoogle** [comment]
Thank you for the contribution! Please squash your commits?

**Comment by wasabigeek** [comment]
Is there a plan to update the sample for later Django versions?

**Comment by pierrei** [comment]
@nathanielmanistaatgoogle: No problem! How do I do that when I've already pushed my commits? Can't you squash when you merge?

**Comment by pierrei** [comment]
@wasabigeek: No plan for me at least. I just wanted to help people to make it work in the first place :)

**Comment by waprin** [comment]
@wasabigeek @pierrei I have new Samples here: https://github.com/google/oauth2client/pull/636 , feel free to take a look/comment . I think Django samples belong more there then here since the only Django specific stuff is the auth (oauth2client used to be part of this repo). So my inclination is just to delete this sample and redirect users there. What do you think?

And @pierrei are you actually using Django 1.4? Or just trying to be helpful? Because if you are then maybe I shouldn't delete them.

**Comment by busunkim96** [comment]
Django samples have been removed.

**Pull request closed without merging**
