### PR TITLE
chore: prevent normalization of semver versioning

### PR DESCRIPTION
**Pull request by dandhlee**
When there is a patch version added to semver versioning, setuptools.setup(version) will normalize the versioning from `-patch` to `.patch` which is not correct SEMVER versioning. The added feature with setuptools.sic(version) will prevent this from happening.

### CODE REVIEW

**Comment by parthea** [comment]
This is on hold as @dandhlee confirmed that this requires a minimum version of `setuptools`.

**Comment by dandhlee** [comment]
All is good now, if there is no problem with Kokoro pre-submits then it's fine, otherwise I'm working through the repositories to make necessary change and workarounds.

**Comment by busunkim96** [comment]
@dandhlee This repo doesn't declare `setuptools` as a direct dependency, so please use the workaround to avoid breaking folks. 

You won't see a failure in CI since the tests will install the latest version of `setuptools` in a fresh environment.

**Comment by dandhlee** [comment]
Understood, will make those changes around! Sorry for that 😓

**Review by parthea — APPROVED** [review]
LGTM

**Pull request merged**
