### PR TITLE
Fix : fix mac and linux commands typo

### PR DESCRIPTION
**Pull request by ellie-ys**
Fix typo

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-api-python-client/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #<> 🦕

### CODE REVIEW

**Comment by ellie-ys** [comment]
Fix typo

**Comment by ellie-ys** [comment]
Fix typo : mac and linux commands

**Comment by parthea** [comment]
Hi @ellie-ys , Please could you sign the CLA?

**Comment by parthea** [comment]
I'm going to close this PR as the CLA is not signed but please feel free to re-open it.

**Pull request closed without merging**
