### PR TITLE
fix: add static discovery docs 

### LINKED ISSUE #1214: Published package is missing discovery files in discovery_cache
Many thanks to the @wyk9787 for noticing this and reaching out.

All calls to `discovery.build()` using `2.0.0` fail with "unknown api name or version".

```python
from googleapiclient import discovery

client = discovery.build("cloudprofiler", "v2")
```

This is because the published package has no `discovery_cache/documents` directory. 

1. `python3 -m venv env`
2. `source env/bin/activate`
3. `python3 -m pip install google-api-python-client`
4. `ls env/lib/python*/site-packages/googleapiclient/discovery_cache`

```
busunkim@busunkim:~/github$ ls env/lib/python*/site-packages/googleapiclient/discovery_cache
appengine_memcache.py  base.py  file_cache.py  __init__.py  __pycache__
```

### PR DESCRIPTION
**Pull request by busunkim96**
Fixes #1214 

The [MANIFEST.in](https://packaging.python.org/guides/using-manifest-in/) controls which files are included in the published package.

You can verify that this fixes the problem (missing discovery docs leading to failing `discovery.build()` calls) by building the package and installing the library from the tarfile.

- `python3 -m venv env`
- `source env/bin/activate`
- `python3 -m setup.py sdist`
- `python3 -m pip install dist/google-api-python-client-2.0.0.tar.gz`

```
(env) busunkim@busunkim:~/github/google-api-python-client$ python3
Python 3.6.9 (default, Feb 24 2020, 21:10:07) 
[GCC 9.2.1 20190909] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import googleapiclient
>>> from googleapiclient import discovery
>>> client = discovery.build("cloudprofiler", "v2")
>>> 
```

### CODE REVIEW

**Review by parthea — APPROVED** [review]
LGTM, Thanks @busunkim96 !

**Comment by jdelalande** [comment]
Hello,
it seams that i am having a similar issue with building service with "mybusiness" on "v4". Do you have any idea how i could fix it ? should mention a specific discovery ? (nb : was using this one: "https://developers.google.com/my-business/samples/mybusiness_google_rest_v4p5.json")
Thanks

**Comment by busunkim96** [comment]
@jdelalande Please see #1225

**Comment by enkeyz** [comment]
> @jdelalande Please see #1225

Where can I find an API's discovery url? My issue: https://github.com/googleapis/google-api-python-client/issues/1238

**Pull request merged**
