### PR TITLE
fix by ruff

### PR DESCRIPTION
**Pull request by YoshitakaNaraoka**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-api-python-client/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by parthea** [comment]
Hi @YoshitakaNaraoka, Thanks for opening a PR. Please could you sign the CLA?

**Comment by parthea** [comment]
View this [failed invocation](https://github.com/googleapis/google-api-python-client/pull/2304/checks?check_run_id=19977940309) of the CLA check for more information.

 If you are not currently covered under a CLA, please visit https://cla.developers.google.com/. Once you've signed, follow the "New Contributors" link at the bottom of that page to update this check.

**Comment by YoshitakaNaraoka** [comment]
I already 署名 cla

**Comment by parthea** [comment]
Regrettably, the CLA status is still not satisfied. Please can you double check the email address used for the CLA?

`***@hotmail.com	Need CLA`

**Comment by leahecole** [comment]
Closing as obsolete, feel free to reopen once CLA issues are resolved

**Pull request closed without merging**
